name: hivetodo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0-178.1.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  flutter: 
    sdk: flutter
  hive: ^2.0.4
  path_provider: ^2.0.6
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.5

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

